services:
  - type: web
    name: finance-app
    runtime: docker
    dockerfilePath: ./finance-app/Dockerfile.render
    dockerContext: ./finance-app
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: AUTH_USER
        sync: false
      - key: AUTH_PASS
        sync: false
